from smolagents import tool

from services.ragify import RagifyPipe
from core.parser import Parser
from core.DBHandler import VectorDBManager
from dotenv import load_dotenv
load_dotenv()

@tool
def ragify_document(file_path : str, collection_name: str) -> None:
    """
    This is a Tool that is in charge of ragifying a document located at file_path into a vector database collection.
    Args:
        file_path: Path to the document to ragify.
        collection_name: Name of the collection in the vector database to store the document chunks alongside their embeddings & metadata.
    Returns :
        None
    """
    ragify = RagifyPipe()
    ragify(file_path,collection_name)
    print(f"Document at {file_path} has been ragified into collection {collection_name}.")

@tool
def parse_document(file_path : str) -> str:
    """
    This is a Tool that is in charge of parsing a document (PDF,PPTX,DOCX) located at file_path into markdown text with pages numbered.
    Args:
        file_path: Path to the document to parse.
    Returns :
        String content of the parsed document in markdown format with page numbers.
    """
    parser = Parser()
    doc = parser.parse(file_path)
    markdown_with_pages = parser.export_to_markdown_with_page_numbers(doc)
    return markdown_with_pages


@tool
def list_collections() -> list[str]:
    """
    This is a Tool that is in charge of listing all available collections in the vector database.
    Returns :
        List of collection names as strings.
    """
    db_manager = VectorDBManager()
    collections = db_manager.list_collections()
    return collections

@tool
def query_collection(collection_name : str, query_text : str, k : int =5) -> str:
    """
    This is a Tool that is in charge of querying a specific collection in the vector database with a text query.
    Args:
        collection_name: Name of the collection to query.
        query_text: The text query to search for.
        k: Number of top similar documents to retrieve.
    Returns :
        String content of the retrieved documents concatenated.
    """
    db_manager = VectorDBManager()
    results = db_manager.query(collection_name,query_text,k)
    combined_content = "\n----------------------------\n\n-------------------------\n".join([f"Source: {doc.metadata.get('source', 'Unknown')} (Page {str(doc.metadata.get('page_numbers', 'Unknown'))})\nContent:\n{doc.page_content}" for doc in results])
    return combined_content

#@tool
#def provide_images_filepaths(filepaths : list[str],session_id : str) -> None:
#    """
#    This is a Tool that is in charge of providing filepaths to the images you generated on your last query, use it only after generating a set of images.
#    It will inform the user & other tasks of existence of these new images generated by you, so they can locate them.
#    Always call these tool if you visualized & generated any images after a query, and do it just before final answer.
#    Args:
#        filepaths: List of the file paths you saved the generated images in.
#        session_id: Currestion Session ID, provided to you, in string.
#    Returns :
#        pd.DataFrame of dataset requested.
#    """
#    if not os.path.isdir(os.environ["SESSIONS_PATH"]):
#        os.mkdir(os.environ["SESSIONS_PATH"])
#    
#    for file in filepaths:
#        if not os.path.exists(file):
#            raise FileNotFoundError(f"Provided Image File Path : {file}, does not exist, please provide valid paths!")
#
#    with open(os.path.join(os.environ["SESSIONS_PATH"],"tracker.json"),'w+') as f:
#        json.dump(filepaths,f)            
#    print("FIle paths of new created images, have been provided!")



#@tool
#def read_text_file(filepath : str) -> str:
#    """
#    This is a Tool that is in charge of reading a text file & returning the contents of it.
#    Args:
#        filepath: File path of the text file you want to read.
#    Returns :
#        String content of the text file.
#    """
#    if not os.path.exists(filepath):
#        raise FileNotFoundError(f"Provided File Path : {filepath}, does not exist, please provide valid path!")
#    with open(filepath,'r') as f:
#        return f.read()
    

if __name__ == "__main__":
    print(query_collection("hotels",""))